In [1]:
import numpy as np

In [4]:
l=[[1,2,3],[3,4,5],[5,6,7]]

In [5]:
l1=[[1,2,3],[3,4,5],[5,6,7]]

In [6]:
l2=np.dot(l,l1)

In [7]:
l2

array([[22, 28, 34],
       [40, 52, 64],
       [58, 76, 94]])

In [8]:
l=np.array([1,2,3])
l1=np.array([4,5,6])
print(np.outer(l,l1))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [9]:
l=np.array([1,2,3])
l1=np.array([4,5,6])
print(np.cross(l,l1))

[-3  6 -3]


In [12]:
l=np.array([[5,2],[3,4]])
print(np.linalg.det(l))

13.999999999999996


In [13]:
l=np.array([1,2,3])
l1=np.array([4,5,6])
print(np.inner(l,l1))

32


In [15]:
l=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.eig(l)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [16]:
l=np.array([1,2,3])
l1=np.array([4,5,6])
np.kron(l,l1)

array([ 4,  5,  6,  8, 10, 12, 12, 15, 18])

In [18]:
l=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.cond(l)

3.813147060626918e+16

In [25]:
np.trace(l)

15

In [26]:
np.transpose(l)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])